global:
  scrape_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - 172.31.10.45:9093

#rule_files:
#  - "rules_prometheus.yml"


scrape_configs:
  - job_name: 'sand-tabloide'
    static_configs:
      - targets: ['172.31.25.127:9100']

  - job_name: 'integracoes'
    static_configs:
      - targets: ['172.31.28.4:9100']

  - job_name: 'cartaz-prod'
    static_configs:
      - targets: ['172.31.44.83:9100']

  - job_name: 'api-cartaz'
    static_configs:
      - targets: ['172.31.29.126:9100']

  - job_name: 'socket-io'
    static_configs:
      - targets: ['172.31.14.34:9100']

  - job_name: 'fluxo'
    static_configs:
      - targets: ['172.31.30.109:9100']
      
  - job_name: 'sand-trade'
    static_configs:
      - targets: ['172.31.14.180:9100']

  - job_name: 'negreiros'
    static_configs:
      - targets: ['172.31.25.210:9100']

  - job_name: 'trade'
    static_configs:
      - targets: ['172.31.18.56:9100']

  - job_name: 'tabloide'
    static_configs:
      - targets: ['172.31.18.255:9100']

  - job_name: 'monitoramento'
    static_configs:
      - targets: ['172.31.10.45:9090']

  - job_name: 'monitoramento-prometheus'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.28.4:8090']
